functionsDirectory = "C:\\news_pwa\\knews-119\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\news_pwa\\knews-119\\public"
publishOrigin = "config"
commandOrigin = "ui"
functions = "C:\\news_pwa\\knews-119\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]